In [1]:
! ls

 05_hatzis_2011_clinical.csv    05_hatzis_2011_suppData.csv
 05_hatzis_2011_gex.csv        'analysis and ML.ipynb'
 05_hatzis_2011.ipynb	        GSE25055_series_matrix.csv
 05_hatzis_2011_merge.csv       nihms905547.pdf
 05_hatzis_2011_merging.ipynb

In [2]:
import pandas as pd
df = pd.read_csv('GSE25055_series_matrix.csv', skiprows=87, index_col=0)
df.head()

,GSM615096,GSM615097,GSM615098,GSM615099,GSM615100,GSM615101,GSM615102,GSM615103,GSM615104,GSM615105,...,GSM615396,GSM615397,GSM615398,GSM615399,GSM615400,GSM615401,GSM615402,GSM615403,GSM615404,GSM615405
ID_REF,,,,,,,,,,,,,,,,,,,,,
1007_s_at,12.359267,12.613243,11.551397,11.828700,11.983987,11.968264,12.941168,12.564150,12.346389,12.582410,...,12.573303,12.263917,12.322112,11.794257,11.351815,12.135865,11.982492,11.721887,11.066133,10.703124
1053_at,8.021741,7.842947,8.776267,9.523877,6.836237,8.665255,8.413069,8.292229,8.204654,7.789927,...,8.857717,9.122348,8.119891,6.884395,8.339561,8.633192,9.451202,8.955527,9.489278,8.813052
117_at,8.294244,5.474758,8.197121,7.907263,8.625010,7.480015,8.780554,9.817384,8.328537,7.512418,...,8.652585,8.045060,7.542309,8.116405,7.472991,9.783710,8.210670,8.980073,7.945081,9.025983
121_at,10.840949,11.715159,10.715077,10.750475,10.827725,10.767155,10.945211,10.905835,11.074558,10.777823,...,11.051351,11.042565,11.210478,12.650804,9.701292,9.830411,9.354246,10.727569,9.552854,9.693816
1255_g_at,7.874062,7.347955,6.523880,6.478643,7.336754,6.641128,7.988518,6.809615,6.271495,6.860993,...,7.069973,6.210511,7.358542,7.669829,7.417731,7.357560,7.178217,8.242348,7.353828,5.531112

In [3]:
df = df.T

In [4]:
df.drop('!series_matrix_table_end', axis=1, inplace=True)

In [5]:
df.reset_index(inplace=True)

In [6]:
df.rename(columns={'index':'patient_ID'}, inplace=True)

In [7]:
df.head(2)
df.shape

(310, 22284)

In [8]:
cd = pd.read_csv('05_hatzis_2011_clinical.csv')
cd.shape

(310, 20)

In [9]:
merg = pd.merge(cd, df, on='patient_ID')
merg.head()

,patient_ID,age,er_ihc,pr_ihc,her2,NAC,stage,nodal_stat,ajcc_stage,grade,...,AFFX-r2-Hs28SrRNA-5_at,AFFX-r2-Hs28SrRNA-M_at,AFFX-r2-P1-cre-3_at,AFFX-r2-P1-cre-5_at,AFFX-ThrX-3_at,AFFX-ThrX-5_at,AFFX-ThrX-M_at,AFFX-TrpnX-3_at,AFFX-TrpnX-5_at,AFFX-TrpnX-M_at
0,GSM615096,37.8,P,P,N,Taxane/Anthracycline,T2,N1,IIB,2,...,9.047564,11.274337,17.356685,17.004035,3.882092,4.345965,5.363505,2.262616,3.963081,2.511676
1,GSM615097,45.8,P,P,N,Taxane/Anthracycline,T3,N1,IIIA,2,...,8.765575,11.287301,18.404677,18.143576,4.319704,4.686218,4.604493,3.064326,4.201127,2.657320
2,GSM615098,40.7,N,N,N,Taxane/Anthracycline,T3,N0,IIB,3,...,9.450242,11.308490,16.304500,15.988321,4.025823,5.339677,4.950814,4.890142,4.014649,2.802313
3,GSM615099,40.8,N,N,N,Taxane/Anthracycline,T2,N1,IIB,4=Indeterminate,...,8.466331,10.208604,16.190139,15.807992,4.651150,4.270966,5.020021,3.692463,4.490109,3.305651
4,GSM615100,35.5,P,P,N,Taxane/Anthracycline,T3,N1,IIIA,2,...,8.721290,11.110014,16.767231,16.485521,4.995794,5.387855,5.055784,5.843128,3.132794,3.661308

In [10]:
merg.shape

(310, 22303)

In [11]:
#merg.to_csv('05_hatzis_2011_merge.csv', index=False)

In [12]:
df.head()

ID_REF,patient_ID,1007_s_at,1053_at,117_at,121_at,1255_g_at,1294_at,1316_at,1320_at,1405_i_at,...,AFFX-r2-Hs28SrRNA-5_at,AFFX-r2-Hs28SrRNA-M_at,AFFX-r2-P1-cre-3_at,AFFX-r2-P1-cre-5_at,AFFX-ThrX-3_at,AFFX-ThrX-5_at,AFFX-ThrX-M_at,AFFX-TrpnX-3_at,AFFX-TrpnX-5_at,AFFX-TrpnX-M_at
0,GSM615096,12.359267,8.021741,8.294244,10.840949,7.874062,8.341292,8.256335,6.485966,6.495728,...,9.047564,11.274337,17.356685,17.004035,3.882092,4.345965,5.363505,2.262616,3.963081,2.511676
1,GSM615097,12.613243,7.842947,5.474758,11.715159,7.347955,9.419005,7.983681,7.330512,7.332244,...,8.765575,11.287301,18.404677,18.143576,4.319704,4.686218,4.604493,3.064326,4.201127,2.657320
2,GSM615098,11.551397,8.776267,8.197121,10.715077,6.523880,9.297479,7.820261,6.423794,10.066291,...,9.450242,11.308490,16.304500,15.988321,4.025823,5.339677,4.950814,4.890142,4.014649,2.802313
3,GSM615099,11.828700,9.523877,7.907263,10.750475,6.478643,8.698516,7.526617,7.276040,10.399704,...,8.466331,10.208604,16.190139,15.807992,4.651150,4.270966,5.020021,3.692463,4.490109,3.305651
4,GSM615100,11.983987,6.836237,8.625010,10.827725,7.336754,9.599059,8.312127,6.832232,7.090151,...,8.721290,11.110014,16.767231,16.485521,4.995794,5.387855,5.055784,5.843128,3.132794,3.661308

In [13]:
df.to_csv('05_hatzis_2011_gex.csv')